### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aydinhp1** [vanhbakaa/Tapswap#1]
Traceback (most recent call last):
  File "/root/Tapswap/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/Tapswap/main.py", line 8, in main
    await process()
  File "/root/Tapswap/bot/utils/launcher.py", line 98, in process
    await run_tasks(tg_clients=tg_clients)
  File "/root/Tapswap/bot/utils/launcher.py", line 167, in run_tasks
    await asyncio.gather(*tasks)
  File "/root/Tapswap/bot/core/tapper.py", line 634, in run_tapper
    await Tapper(tg_client=tg_client, lock=lock, account_gap=account_gap).run(proxy=proxy, ua=ua)
  File "/root/Tapswap/bot/core/tapper.py", line 390, in run
    self.chr_gap = await extract_gap(chq=self.account_gap['chq'], chr=self.account_gap['chr'])
                                         ~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x7fc5f8e5d6d0>

**Comment by vanhbakaa** [comment]
Bro please read instruction before use
